name: Run Tests

on:
  push:
    branches: [ main ] # Run on pushes to the main branch
  pull_request:
    branches: [ main ] # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on common LTS Node versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use the latest checkout action

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # Use the latest setup-node action
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use ci for faster, deterministic installs

    - name: Run tests
      run: npm test